server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/task_manager}
#    url: ${DBMS_CONNECTION:jdbc:mysql://host.docker.internal:3306/task_manager}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:Kieuhieu2@}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

logging:
  level:
    org:
      springframework:
        boot=DEBUG:

file:
    upload-dir: FileOfGroup/
